cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - open-tacos/node_modules/
    - open-tacos/.cache
    - public

image: registry.gitlab.com/openbeta/openbeta-nodejs-docker:16.3

variables:
  GIT_DEPTH: 1
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  IMAGE_CURRENT: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  IMAGE_LATEST:  $CI_REGISTRY_IMAGE:latest

# Job name must be 'pages' in order for GitLab to deploy build to static site
gatsby-build:
  only: # Only run for these branches
  - develop
  - main
  - gitlab-debug

  stage: build

  tags:
  - docker

  before_script:
  - mkdir -p open-tacos 
  - mv content open-tacos
  # we need to move build output dir back down 1 level for GitLab pages to work
  - '[ -d public ] && mv public open-tacos'
  - cd open-tacos && ls -la
  - git init .  && git remote add origin https://github.com/OpenBeta/open-tacos
  - git pull --depth $GIT_DEPTH origin develop
  - git checkout develop
  - if [ "$FORCE_CLEAN" == "true" ]; then rm -rf node_modules; fi;
  - yarn install --no-progress
  - if [ "$FORCE_CLEAN" == "true" ]; then ./node_modules/.bin/gatsby clean; fi;

  script:
  - ./node_modules/.bin/gatsby build
  - mv public $CI_PROJECT_DIR

docker-build:
  only: # Only run for these branches
  - develop
  - main
  - gitlab-debug

  stage: build

  tags:
    - docker

  needs: [gatsby-build]

  image: docker:20.10.10

  services:
     - docker:20.10.10-dind

  before_script:
     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  script:
     - docker pull $IMAGE_LATEST || true
     - docker build --cache-from $IMAGE_LATEST --tag $IMAGE_CURRENT --tag $IMAGE_LATEST .
     - docker push $IMAGE_CURRENT
     - docker push $IMAGE_LATEST
