cache:
  paths:
    - open-tacos/node_modules/
    - open-tacos/.cache
    - public

image: registry.gitlab.com/openbeta/openbeta-nodejs-docker:16.3

variables:
  GIT_DEPTH: 5
  DOCKER_DRIVER: overlay2

# Job name must be 'pages' in order for GitLab to deploy build to static site
pages:
  only: # Only run for these branches
  - develop
  - main
  - gitlab-debug

  stage: build

  tags:
  - docker

  before_script:
  # - apt-get update && apt-get install -y git
  - mkdir -p open-tacos 
  - mv content open-tacos
  # we need to move build output dir to top level for GitLab pages to work
  - '[ -d public ] && mv public open-tacos'
  - cd open-tacos && ls -la
  - git init .  && git remote add origin https://github.com/OpenBeta/open-tacos
  - git pull origin develop
  - git checkout develop
  - cat gatsby-config.js
  - yarn install --no-progress

  script:
  - ./node_modules/.bin/gatsby build
  - mv public $CI_PROJECT_DIR

  artifacts:  # Use by GitLab pages
    paths:
    - public
