cache:
  paths:
    - open-tacos/node_modules/
    - open-tacos/.cache
    - open-tacos/public

image: node:16.3-buster-slim

variables:
  GIT_DEPTH: 1
  DOCKER_DRIVER: overlay2

# Job name must be 'pages' in order for GitLab to deploy to static site
pages:
  only: # Only run for these branches
  - develop
  - main
  - gitlab-debug

  stage: build

  tags:
  - docker

  before_script:
  - apt-get update && apt-get install -y git
  - ls -la
  - mkdir -p open-tacos 
  - ln -s $CI_PROJECT_DIR/content open-tacos/content
  - ln -s $CI_PROJECT_DIR/public open-tacos/public
  - cd open-tacos && ls -la
  - git init .  && git remote add origin https://github.com/OpenBeta/open-tacos
  - git pull --depth=1 origin develop
  - git checkout develop
  - yarn install --no-progress

  script:
  - ./node_modules/.bin/gatsby build
  
  after_script:
  - mv build $CI_PROJECT_DIR

  artifacts:  # Use by GitLab pages
    paths:
    - public
